version: "3.9"

networks:

  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:

  db_vol:
    name: db_vol

  upload:
    name: upload

services:

  db:
    image: postgres:14
    container_name: db
    env_file: .env
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data/${DB_NAME}
    networks:
      - ft_transcendence

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: backend:img
    container_name: backend
    env_file: .env
    restart: always
    depends_on:
      - db
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    volumes:
      - upload:/upload
    networks:
      - ft_transcendence

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: frontend:img
    container_name: frontend
    env_file: .env
    restart: always
    depends_on:
      - pong
    ports:
      - "${HOST_PORT}:${FRONT_PORT}"
    networks:
      - ft_transcendence

  pong:
    build:
      context: .
      dockerfile: pong.Dockerfile
    image: pong:img
    container_name: pong
    env_file: .env
    restart: always
    depends_on:
      - backend
    ports:
      - "${PONG_PORT}:${PONG_PORT}"
    networks:
      - ft_transcendence