version: "3.9"

networks:
  ft_trancendence:
    name: ft_trancendence
    driver: bridge

volumes:
  db_vol:
    name: db
    driver_opts:
      type: none
      o: bind
      device: /ft_data/db
  upload:
    name: upload
    driver_opts:
      type: none
      o: bind
      device: /ft_data/upload

services:

  db:
    image: postgres:14
    container_name: db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${DB_AUTH}
    restart: always
    ports:
      - "11080:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data/${DB_NAME}
    networks:
      - ft_trancendence

  pong:
    build:
      context: ./pong
    image: pong:img
    container_name: pong
    restart: always
    ports:
      - "12080:12080"
    networks:
      - ft_trancendence

  backend:
    build:
      context: ./backend
    image: backend:img
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - upload:/backend/upload
    networks:
      - ft_trancendence



