version: '3'

volumes:
  db_vol:
    name: db_vol
    driver_opts:
      type: none
      o: bind
      device: ../db_vol

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file: .env
    restart: always
    ports:
      - "11080:5432"
    volumes:
      - db_vol:/var/lib/postresql/data


  
